
-- Supprime les tables si elles existent déjà pour garantir un état propre.
-- Le "CASCADE" supprime aussi tout ce qui dépend de la table.
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS restaurant_status CASCADE;

-- Table pour les articles du menu
CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT, -- Colonne pour la description de l'article
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT
);

-- Table for restaurant status
CREATE TABLE restaurant_status (
  id INT PRIMARY KEY DEFAULT 1,
  is_open BOOLEAN NOT NULL DEFAULT TRUE
);

-- Insert initial status (open by default)
INSERT INTO restaurant_status (id, is_open) VALUES (1, TRUE) ON CONFLICT (id) DO NOTHING;

-- Table pour les commandes
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items JSONB NOT NULL, -- Store array of items as JSONB
  total NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'submitted', -- e.g., 'submitted', 'accepted', 'refused', 'preparing', 'ready', 'delivered'
  delivery_slot TEXT, -- Optional delivery time slot
  refusal_reason TEXT -- Optional reason for refusal
);

-- Activer les publications en temps réel pour la table des commandes
-- L'erreur "already exists" sur la ligne suivante est normale et peut être ignorée.
-- Elle n'empêchera pas la création des tables.
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
