
-- Supprime les tables Wok si elles existent déjà pour garantir un état propre.
DROP TABLE IF EXISTS wok_bases CASCADE;
DROP TABLE IF EXISTS wok_pulpes CASCADE;
DROP TABLE IF EXISTS wok_favoris CASCADE;
DROP TABLE IF EXISTS wok_sauces CASCADE;
DROP TABLE IF EXISTS wok_toppings CASCADE;

-- Table pour les bases du Wok
CREATE TABLE wok_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL
);

-- Table pour les pulpes du Wok
CREATE TABLE wok_pulpes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL
);

-- Table pour les favoris du Wok
CREATE TABLE wok_favoris (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL
);

-- Table pour les sauces du Wok
CREATE TABLE wok_sauces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

-- Table pour les toppings du Wok
CREATE TABLE wok_toppings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL
);
